# Generated by Django 4.1.8 on 2024-02-28 03:54

import app.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to=app.utils.rename_imagefile_to_uuid)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'app_userprofile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='전자세금계산서',
            fields=[
                ('seq_no', models.CharField(db_collation='Korean_Wansung_CI_AS', db_column='SEQ_NO', max_length=4, primary_key=True, serialize=False)),
                ('사업자번호', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=20)),
                ('매입매출구분', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=1)),
                ('작성일자', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=10)),
                ('승인번호', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=30)),
                ('발급일자', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=10)),
                ('전송일자', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=10)),
                ('공급자사업자등록번호', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=12)),
                ('공급자상호', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=30)),
                ('공급자대표자명', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=20)),
                ('공급자주소', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=100)),
                ('공급받는자사업자등록번호', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=12)),
                ('공급받는자상호', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=100)),
                ('공급받는자대표자명', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=30)),
                ('공급받는자주소', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=100)),
                ('합계금액', models.DecimalField(decimal_places=0, max_digits=15)),
                ('공급가액', models.DecimalField(decimal_places=0, max_digits=15)),
                ('세액', models.DecimalField(decimal_places=0, max_digits=15)),
                ('전자세금계산서분류', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=20)),
                ('전자세금계산서종류', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=20)),
                ('발급유형', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=20)),
                ('비고', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=50)),
                ('영수청구구분', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=10)),
                ('공급자이메일', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=100)),
                ('공급받는자이메일1', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=100)),
                ('공급받는자이메일2', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=100)),
                ('품목일자', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=10)),
                ('품목명', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=300)),
                ('품목규격', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=10)),
                ('품목수량', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=10)),
                ('품목단가', models.DecimalField(decimal_places=0, max_digits=15)),
                ('품목공급가액', models.DecimalField(decimal_places=0, max_digits=15)),
                ('품목세액', models.DecimalField(decimal_places=0, max_digits=15)),
                ('품목비고', models.CharField(db_collation='Korean_Wansung_CI_AS', max_length=300)),
                ('crt_dt', models.CharField(db_collation='Korean_Wansung_CI_AS', db_column='Crt_Dt', max_length=8)),
                ('slip_dt', models.CharField(db_collation='Korean_Wansung_CI_AS', db_column='Slip_Dt', max_length=8)),
                ('slip_acnt_cd', models.CharField(db_collation='Korean_Wansung_CI_AS', db_column='Slip_Acnt_Cd', max_length=10)),
                ('slip_yn', models.CharField(db_collation='Korean_Wansung_CI_AS', db_column='Slip_YN', max_length=1)),
            ],
            options={
                'db_table': '전자세금계산서',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='전자세금계산서스크래핑관리',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crt_dt', models.CharField(db_collation='Korean_Wansung_CI_AS', db_column='crt_dt', max_length=8)),
                ('seqno_lastTry', models.CharField(db_collation='Korean_Wansung_CI_AS', db_column='seqno_lastTry', max_length=5)),
            ],
            options={
                'db_table': '전자세금계산서스크래핑관리',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='blog_authors_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blog_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('new_law', models.BooleanField(default=False)),
                ('youtube_url', models.URLField(blank=True)),
                ('important_grade', models.CharField(choices=[('option7', '매우중요'), ('option8', '중요'), ('option9', '기본'), ('option10', '상식')], default='option8', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogposts', to='app.blogauthor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='app.blogcategory')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='blog_post_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.blogcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.blogpost')),
            ],
        ),
    ]
