# Generated by Django 4.1.8 on 2024-02-28 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_전자세금계산서_전자세금계산서스크래핑관리_blogauthor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'managed': False},
        ),
    ]
