# Generated by Django 4.1.8 on 2024-02-28 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_blogcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={},
        ),
    ]
