# Generated by Django 4.1.8 on 2024-02-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blogcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='important_grade',
            field=models.CharField(choices=[('1', '매우중요'), ('2', '중요'), ('3', '기본'), ('4', '상식')], default='3', max_length=20),
        ),
    ]
